name: Static analysis
# Run static analysis only on PRs towards master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: ubuntu-20.04
    env:
      CXX: g++

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch-depth = 0 is equivalent to entire commit-history
          fetch-depth: 0
      # Sonar wants the target branch, but actions/checkout only fetches the current ref
      - run: git fetch origin develop:refs/remotes/origin/master
      - name: Restore cache for sonar analysis
        uses: actions/cache@v1
        env:
          cache-name: cache-sonar
        with:
          path: /home/runner/.sonarcache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}
      - uses: ottojo/sonarscanner-github-action@master
      - name: Install build-wrapper
        run: |
          mkdir /home/runner/buildwrapper
          wget -O /home/runner/buildwrapper/wrapper.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip /home/runner/buildwrapper/wrapper.zip -d /home/runner/buildwrapper
          echo ::set-env name=PATH::$PATH:/home/runner/buildwrapper/build-wrapper-linux-x86
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: Build
        run: |
          cd build
          build-wrapper-linux-x86-64 --out-dir ../bw-output make all -j$(nproc)
      - name: sonar-scanner
        run: |
          sonar-scanner \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.cfamily.cache.path=/home/runner/.sonarcache \
          -Dsonar.cfamily.cache.enabled=true
